<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add Variant Type</name>
   <tag></tag>
   <elementGuidId>6b758bcb-e4aa-440c-afaf-fb4a2879f916</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='add_variant']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#add_variant</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>743189ad-23b8-4f47-ad8f-81f6f46b41a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>98849ad6-8696-4096-8f3d-afbc56e96019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>add_variant</value>
      <webElementGuid>2fdf310c-016d-4f66-a499-6ce40aaadfa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add_variant</value>
      <webElementGuid>b1b3e161-9ba6-44a9-b759-f0d7d8d957df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-light-success mt-2 mb-2</value>
      <webElementGuid>5c6c9c91-b7d3-4e9f-ae8c-358d95c2215d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Variant Type </value>
      <webElementGuid>8e8d243e-0ea8-47bd-8b3a-a921c280a8d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add_variant&quot;)</value>
      <webElementGuid>a8829e0e-eccd-43c9-9da2-2055b97c0503</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='add_variant']</value>
      <webElementGuid>9dcafe09-e829-4b96-86d1-bd1ac3aff116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkedDetail']/div/div[2]/button</value>
      <webElementGuid>6a520525-970b-4fe8-9b91-00b341db345f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SKU'])[1]/following::button[1]</value>
      <webElementGuid>34996e0f-3364-4f69-bdaa-e1f0e30d6160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDR'])[1]/following::button[1]</value>
      <webElementGuid>9caf5529-8259-4932-86b3-9e2a9b2db6cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Weight &amp; Size'])[1]/preceding::button[1]</value>
      <webElementGuid>9e07ecfb-bc71-4480-a325-11ab8321ef6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Variant Type']/parent::*</value>
      <webElementGuid>b33ac826-bf5f-481a-8978-dd0b655740c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>6d28d181-1c24-4848-b9b0-7561c3b34b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'add_variant' and @id = 'add_variant' and (text() = 'Add Variant Type ' or . = 'Add Variant Type ')]</value>
      <webElementGuid>f39f8342-cd1c-428d-a3ef-302fa67577cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
