<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Price_iconVariant0</name>
   <tag></tag>
   <elementGuidId>77ed7d5e-8992-46bf-bbf4-7a3f39a2eabe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='iconVariant0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iconVariant0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>057d8f32-f09d-4a76-884b-8ef750532517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-file-upload text-primary</value>
      <webElementGuid>d6e18595-9ffd-48f8-a5b4-5c36ec7d5cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iconVariant0</value>
      <webElementGuid>32696f43-c766-4d4f-a0ac-30c0e5f062fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iconVariant0&quot;)</value>
      <webElementGuid>295fdda8-8f11-44e8-98ed-e6ebb3168069</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='iconVariant0']</value>
      <webElementGuid>3fe4342f-f7f8-4fa2-9ef0-78314b41ce50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='imageContainerVariant0']/i</value>
      <webElementGuid>14ce1f78-fa59-494b-a064-e6b0dfbd2344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/i</value>
      <webElementGuid>ead226fd-8465-45d9-ba86-17304c23e55e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'iconVariant0']</value>
      <webElementGuid>b8115dfd-997e-49fc-845b-2b1fc626a505</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
