<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Upload Product_icon5</name>
   <tag></tag>
   <elementGuidId>d2945647-f5da-40ed-85e5-50023f157bc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='icon5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#icon5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>bc30b3dc-1330-44b4-9862-e4a1f3d08d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-file-upload text-primary</value>
      <webElementGuid>8e72c42b-de46-4efa-a811-a841de3d26c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>icon5</value>
      <webElementGuid>05588aa9-8295-4896-8429-e3cb2a9eb8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;icon5&quot;)</value>
      <webElementGuid>40db6f0b-ab26-4028-b560-a8fdd1209366</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='icon5']</value>
      <webElementGuid>e5725c8d-6798-468b-9f73-12d2cb2cfce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='imageContainer5']/i</value>
      <webElementGuid>164e17d1-e7ae-4614-9340-c6dbddde3b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/i</value>
      <webElementGuid>fd96481a-8ea7-4dda-a991-41eecb0925bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'icon5']</value>
      <webElementGuid>538cb89f-4754-448e-ba2c-75b59beb5126</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
