<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Upload Product_icon3</name>
   <tag></tag>
   <elementGuidId>79fcb342-0251-4675-bd98-83c499f5a604</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='icon3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#icon3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c7b20fef-6a00-4139-8d97-638b41394ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-file-upload text-primary</value>
      <webElementGuid>2c96e998-00de-4e21-a993-b00ab71d6ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>icon3</value>
      <webElementGuid>26bebae7-d027-456b-85e4-05b6a834ec45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;icon3&quot;)</value>
      <webElementGuid>9614babb-cc8d-4a49-9450-7ee0fd4a6084</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='icon3']</value>
      <webElementGuid>6c7cd347-58aa-44cd-a3f0-8c0fa566feb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='imageContainer3']/i</value>
      <webElementGuid>b6f3f50a-bdd4-42f3-9507-d8e35d988a0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/i</value>
      <webElementGuid>d5523ada-9fa1-4e89-9ea7-5ddc4f404f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'icon3']</value>
      <webElementGuid>54d46bd2-d418-4d5f-a431-b58e175909be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
