<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Upload Product_icon4</name>
   <tag></tag>
   <elementGuidId>3558ba59-42b8-48c2-a876-a638e320f342</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='icon4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#icon4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>556d6eea-a705-42f2-b750-a18bb545b7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-file-upload text-primary</value>
      <webElementGuid>871dfa41-1f85-4e3d-ab65-640581828dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>icon4</value>
      <webElementGuid>f9a1d823-a5c1-4ee5-99b1-38e0e65fecf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;icon4&quot;)</value>
      <webElementGuid>e092c6a3-a4ae-41ac-90e5-d45bd4b91362</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='icon4']</value>
      <webElementGuid>08ad6744-387b-4301-81b9-96c803bce863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='imageContainer4']/i</value>
      <webElementGuid>b3e9cac4-0029-4a51-be71-1ef348967ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/i</value>
      <webElementGuid>7c76f65c-fab6-4586-b342-c6e2939075eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'icon4']</value>
      <webElementGuid>0bf8c749-6cef-4db6-9c48-e067dd859802</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
