<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Upload Product_icon2</name>
   <tag></tag>
   <elementGuidId>fa4e93c7-2c15-4dc4-83ec-bad98884f312</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='icon2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#icon2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>8853081d-dc1f-4e5e-92d8-6be279ccc9a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-file-upload text-primary</value>
      <webElementGuid>0d63b3dd-e97a-4db6-9346-ffad0eccb895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>icon2</value>
      <webElementGuid>78f3977d-0023-49cb-9566-4832a0360c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;icon2&quot;)</value>
      <webElementGuid>c8090c04-9e8b-4dbb-a812-81cb710fd18b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='icon2']</value>
      <webElementGuid>44e02993-69f8-45c0-9ba1-c9c2a7aabe0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='imageContainer2']/i</value>
      <webElementGuid>29889222-3121-4498-a3f8-7b2432dee03e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/i</value>
      <webElementGuid>191730d0-81d4-4de1-a558-72846854c7e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'icon2']</value>
      <webElementGuid>dc1852c3-b291-48e2-97f5-9c70f29770ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
