<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Product Details_checkVariants</name>
   <tag></tag>
   <elementGuidId>a4990e04-193c-42c7-a2a0-0866fbb71090</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkVariants']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkVariants</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b710c926-384d-45f4-9be7-56b3091840fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input h-30px w-60px ml-3 checkedForm</value>
      <webElementGuid>5536c373-f0e7-4c5d-8201-80d22229632e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>73f4d897-a0a9-48ab-8c83-e0d97354bb4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkVariants</value>
      <webElementGuid>5fdc2bdd-0c50-4dcb-af72-454f2e4e0d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ed90d908-a1ea-42ff-a3c2-1d544170bec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-form&quot;)/div[@class=&quot;card mb-3&quot;]/div[@class=&quot;card-body py-4&quot;]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 d-flex justify-content-end&quot;]/div[@class=&quot;form-check form-switch form-check-custom form-check-solid&quot;]/input[@id=&quot;checkVariants&quot;]</value>
      <webElementGuid>99546057-b67b-45b2-9e2a-7beefc1c7a1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkVariants']</value>
      <webElementGuid>c7838527-fd0b-4669-b240-d68302eb6e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-form']/div[4]/div/div/div/div[2]/div/input</value>
      <webElementGuid>e0b745df-6eab-496d-a85a-05d198d1d6a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>5cfa5046-a140-4ac9-8fc4-e16193856985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'checkVariants']</value>
      <webElementGuid>33c13f6f-f601-4946-bf5d-0f7646341a6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
