<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_HS CODE_stock</name>
   <tag></tag>
   <elementGuidId>7576b0ae-1848-4fec-a6c8-536af41d0e80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='basic-url'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(4) > div.input-group > #basic-url</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8b32e9fd-b5db-4cfc-8fa2-67c264f6f056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>ff0d7c8c-768c-4b57-97ab-ffc17cd63240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mb-3</value>
      <webElementGuid>49b72a9e-cef0-42a2-8980-4f69a68d25bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Stock</value>
      <webElementGuid>f957a3eb-1307-4680-95c5-407a76625528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>stock[]</value>
      <webElementGuid>31753aff-d7bc-4df8-ad70-98790590cddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic-url</value>
      <webElementGuid>d808e34a-b61f-4d3f-a9a5-f71f24bb40be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>basic-addon3</value>
      <webElementGuid>9a86c0e3-414e-4503-b579-8008545971f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dynamicVariant&quot;)/tr[1]/td[4]/div[@class=&quot;input-group&quot;]/input[@id=&quot;basic-url&quot;]</value>
      <webElementGuid>7ffb5992-d032-456a-bc22-0a437ad0d703</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='basic-url'])[4]</value>
      <webElementGuid>011e35d4-510e-4182-add2-98b1a1c18985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='dynamicVariant']/tr/td[4]/div/input</value>
      <webElementGuid>83271ee4-3aeb-46b9-a5ad-c1d8d558e78a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/input</value>
      <webElementGuid>ffc42bc2-6905-4b60-b6eb-5f545db4412f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = 'Enter Stock' and @name = 'stock[]' and @id = 'basic-url']</value>
      <webElementGuid>55abdb3f-e05e-4b4f-a246-2e631fc7a49c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
