<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IDR_price</name>
   <tag></tag>
   <elementGuidId>3096b5bc-8cea-4131-b5e2-b1ac8d4755ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='basic-url'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(5) > div.input-group > #basic-url</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>757770f2-fe7e-44b5-9ec4-951168d456e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>954aaa77-5bd3-4382-8850-d580130c8ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mb-3</value>
      <webElementGuid>82c701e3-3878-4fbc-915f-fc7ecc06549b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Price</value>
      <webElementGuid>b8b16350-74c6-4b4f-8720-c2e20436277e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>price[]</value>
      <webElementGuid>ceb1e832-87c2-44ba-af02-e7ba3aceed2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic-url</value>
      <webElementGuid>0450db9e-c0ae-4915-8c8f-c9d6d43cae78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>basic-addon3</value>
      <webElementGuid>5aa545cc-4ef0-455b-9f9d-26fb93234e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dynamicVariant&quot;)/tr[1]/td[5]/div[@class=&quot;input-group&quot;]/input[@id=&quot;basic-url&quot;]</value>
      <webElementGuid>7e8bba2a-b6c7-48bc-8cf3-4a45202ed882</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='basic-url'])[6]</value>
      <webElementGuid>b77916c2-7f8c-4cdf-bb0f-1967e982acbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='dynamicVariant']/tr/td[5]/div/input</value>
      <webElementGuid>ac23dd2a-c999-4923-8c92-94e0e303229b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/input</value>
      <webElementGuid>2b9c96e5-4d1e-47eb-8b0b-98a658306f87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = 'Enter Price' and @name = 'price[]' and @id = 'basic-url']</value>
      <webElementGuid>f87fe021-5917-4416-823f-791aaa754530</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
