<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_HS CODE_hs_code</name>
   <tag></tag>
   <elementGuidId>15da0302-bdc6-4a8a-90ed-6f1ab61b31ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='basic-url'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>887152a7-2a93-4a10-921a-d341b32cffb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c0334cec-0607-4a83-9619-aa411bce9657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mb-3</value>
      <webElementGuid>51bb7690-4b05-46e6-b33d-640bfbe72dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter HS CODE</value>
      <webElementGuid>1a97b6ee-6872-4891-b817-e989c59175d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hs_code[]</value>
      <webElementGuid>ebfd7f69-f2f8-4f00-90dc-73adbd9e749f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic-url</value>
      <webElementGuid>7de071e0-ddfb-4693-aee0-b57892823a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>basic-addon3</value>
      <webElementGuid>97e1c335-2773-4ea3-b144-fc0900551231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dynamicVariant&quot;)/tr[1]/td[3]/div[@class=&quot;input-group&quot;]/input[@id=&quot;basic-url&quot;]</value>
      <webElementGuid>d0c92647-701d-4f5a-97ed-e17990bce0d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='basic-url'])[3]</value>
      <webElementGuid>5791c9c6-5646-4a6e-b95b-f6fc543b2883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='dynamicVariant']/tr/td[3]/div[2]/input</value>
      <webElementGuid>b4fea6f7-0778-4fa9-b90c-dea046bd75b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div[2]/input</value>
      <webElementGuid>80e0b348-62dd-4175-b9dd-ddef048bb71d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = 'Enter HS CODE' and @name = 'hs_code[]' and @id = 'basic-url']</value>
      <webElementGuid>5c78d4c9-04fd-4d0c-b623-42b0f27a7095</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
