<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__length</name>
   <tag></tag>
   <elementGuidId>5767e5ba-c459-4764-8d24-72d9ea628c8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='length']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#length</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc6efcf3-7f86-46ec-8dc6-f10dc1305ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c00bae46-7e8d-4e0d-8dac-fb16e75c187f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control w-50</value>
      <webElementGuid>f85410de-f07c-44c9-a63a-04a08303793c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>length</value>
      <webElementGuid>321f3dc5-7f55-4ee2-997f-721ddf3aa853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>length</value>
      <webElementGuid>b425afa3-5e58-4261-8d92-8ee0fd2a5655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>emailHelp</value>
      <webElementGuid>3a5eed02-31cd-412f-9aa5-bd664f4582cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter length</value>
      <webElementGuid>1b2b59a2-7f1b-4fa4-af72-eb57c3430b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;length&quot;)</value>
      <webElementGuid>433eb2dd-29f7-41f2-aee4-9eeee111fb17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='length']</value>
      <webElementGuid>363acec6-0450-4d8a-9a04-4570f5426b4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-form']/div[5]/div[2]/div/div[4]/div/div/input</value>
      <webElementGuid>299e3d23-be31-43fe-851f-0f26f9b943da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div/div/input</value>
      <webElementGuid>13908353-76d0-48ec-a9b4-55e01d612cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'length' and @name = 'length' and @placeholder = 'Enter length']</value>
      <webElementGuid>0147062b-3184-46ce-9ba7-5ab1ebfd30ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
