<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Box_quantity_per_unit</name>
   <tag></tag>
   <elementGuidId>9368fce0-2f41-46f4-be75-1ce4371504f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='quantity_per_unit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;quantity_per_unit&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6f067c6-9888-422e-bfc4-350dd9887e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>72b4ef17-8163-40ce-9c4d-59fc42693f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control w-50</value>
      <webElementGuid>5ab9fe04-db9a-4af3-b5b7-b27e1574927e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>quantity_per_unit</value>
      <webElementGuid>a15eddaa-3043-4f26-afde-7588ccf7ce30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>emailHelp</value>
      <webElementGuid>a0224e3f-cdd2-40ae-b500-9a6d0bf444ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Product Unit</value>
      <webElementGuid>3958d0fb-ea94-4fee-981f-850a4c006283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unitInput&quot;)/div[@class=&quot;input-group&quot;]/input[@class=&quot;form-control w-50&quot;]</value>
      <webElementGuid>41704681-0ec5-4242-8c2c-538034211e98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='quantity_per_unit']</value>
      <webElementGuid>0962f5df-ee25-4595-bf48-c768e6c49a42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='unitInput']/div/input</value>
      <webElementGuid>c42b7f8b-559d-42f2-bafc-3d11ae735351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>db0e8347-fa13-4ea6-bde3-3a06d237a582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'quantity_per_unit' and @placeholder = 'Enter Product Unit']</value>
      <webElementGuid>611b4343-0dfc-475d-9e55-e71c42c5e64f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
