<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Barcode_barcode</name>
   <tag></tag>
   <elementGuidId>123df64d-fe1c-478e-a0d5-709930ae355e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='basic-url'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>342834ec-5837-4064-a923-3048744074f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>7a66ad38-5ed7-4d8f-9425-f51fa304cfc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mb-3</value>
      <webElementGuid>6a172b72-ddcd-47b8-b3f5-54e5f859fe15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Barcode</value>
      <webElementGuid>26c6fad5-5b47-4d0f-910c-869ea977115f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>barcode[]</value>
      <webElementGuid>618c3d6a-7bea-4078-94a4-6cfee548ae85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic-url</value>
      <webElementGuid>85d66efc-174c-41e3-8f56-c28eb0ff7e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>basic-addon3</value>
      <webElementGuid>389af23e-a873-46c7-bbe7-806835944d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dynamicVariant&quot;)/tr[1]/td[4]/div[@class=&quot;input-group&quot;]/input[@id=&quot;basic-url&quot;]</value>
      <webElementGuid>84088dcf-f6f8-44e8-b42d-d8dc759e9015</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='basic-url'])[5]</value>
      <webElementGuid>927ec75f-9930-4f37-9115-084c89b1ba1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='dynamicVariant']/tr/td[4]/div[2]/input</value>
      <webElementGuid>25a64a04-6ea2-42dd-bb25-080c9fe01371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div[2]/input</value>
      <webElementGuid>6ded6892-7f78-4d1f-a168-faa5ad3c2de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = 'Enter Barcode' and @name = 'barcode[]' and @id = 'basic-url']</value>
      <webElementGuid>b5399c42-3c08-4faf-9cbd-5e7756c32c8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
