<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Carton</name>
   <tag></tag>
   <elementGuidId>04ef30d5-1360-48cc-8f5e-472fb1f92b06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id = 'select2-unitSelect-result-onil-Carton' and (text() = 'Carton' or . = 'Carton')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>e419dde5-89b5-4486-9cab-909263a71700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--selectable select2-results__option--highlighted</value>
      <webElementGuid>ee29c2e4-a7a4-4219-b1b8-9b34d1ca1427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-unitSelect-result-onil-Carton</value>
      <webElementGuid>0f26d462-c731-4219-94c6-ff7aec224425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d7fb0928-74cd-4110-a85a-462ecabc4971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-data-select2-unitSelect-result-onil-Carton</value>
      <webElementGuid>d839cb7b-20da-46f9-ac5c-037400f9890a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f49f92a7-9527-4071-bf3b-b5d4750b40d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Carton</value>
      <webElementGuid>be810138-af12-4082-9a2f-43065715bbf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-unitSelect-result-onil-Carton&quot;)</value>
      <webElementGuid>88f16e5b-6b44-436c-a1c7-171dc0c8889f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-unitSelect-result-onil-Carton' and (text() = 'Carton' or . = 'Carton')]</value>
      <webElementGuid>1eb84884-3be8-4b44-bcce-bb6ea47cd15a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
