<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Gunny</name>
   <tag></tag>
   <elementGuidId>966ab556-d117-4b43-908f-58d01ff1b519</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id = 'select2-unitSelect-result-8v3q-Gunny' and (text() = 'Gunny' or . = 'Gunny')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>0d873d9a-2c00-47c1-bd34-158122526ba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--selectable select2-results__option--highlighted</value>
      <webElementGuid>30974f20-c521-4654-8f48-2d6bc064e523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-unitSelect-result-8v3q-Gunny</value>
      <webElementGuid>942c40f1-3ae1-4123-bf48-3e5e9a955cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>efb4de18-4b38-41ea-8324-11390faa8721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-data-select2-unitSelect-result-8v3q-Gunny</value>
      <webElementGuid>2182d604-5e20-4436-94dd-183d82d2c484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1f20b1c7-8f6c-40a4-a524-ff584bd8da86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gunny</value>
      <webElementGuid>7298f635-6ecf-498c-84c2-71f94ea719bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-unitSelect-result-8v3q-Gunny&quot;)</value>
      <webElementGuid>9d05c717-d9f4-4268-83c2-8dc3b47a019c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-unitSelect-result-8v3q-Gunny' and (text() = 'Gunny' or . = 'Gunny')]</value>
      <webElementGuid>d904d52e-c4d5-4f17-badc-4a218a39fd23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
