<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Pcs</name>
   <tag></tag>
   <elementGuidId>8aa319de-3087-4324-b106-08dc0a986e1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id = 'select2-unitSelect-result-ffzh-Pcs' and (text() = 'Pcs' or . = 'Pcs')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>0b664049-cdf1-429f-9a43-442eaeb10fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--selectable select2-results__option--highlighted</value>
      <webElementGuid>8583c390-3b2e-430d-97bb-50b9e2639ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-unitSelect-result-ffzh-Pcs</value>
      <webElementGuid>2b0b15ac-0914-455b-8ee5-60649db620f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>247b0c68-e15b-4ec8-aa39-ed7cde4cdd37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-data-select2-unitSelect-result-ffzh-Pcs</value>
      <webElementGuid>c59ef050-fa36-463f-8ebb-93bc8af5c31a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>28097b75-2ead-4cd7-86ab-5f2955555885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pcs</value>
      <webElementGuid>dfa5104f-5e5f-47cc-8b1d-630e62954c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-unitSelect-result-ffzh-Pcs&quot;)</value>
      <webElementGuid>8543d669-900c-4e7b-b4b2-4d937982d75d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-unitSelect-result-ffzh-Pcs' and (text() = 'Pcs' or . = 'Pcs')]</value>
      <webElementGuid>d7a56c48-5ce7-4488-a25f-cd34ec41e452</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
