<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Pack</name>
   <tag></tag>
   <elementGuidId>9f8752e0-bb57-4755-9e91-529b86960b32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id = 'select2-unitSelect-result-a4a8-Pack' and (text() = 'Pack' or . = 'Pack')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5166b697-8204-4ffd-af93-cd562dc0ed2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--selectable select2-results__option--highlighted</value>
      <webElementGuid>89b8b35c-e1f5-449c-8c3c-42c5606cb27c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-unitSelect-result-a4a8-Pack</value>
      <webElementGuid>e61cebd6-b75b-4ce1-b36f-6ad2924e7e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>012c6213-514b-45a7-adf7-e7ba337bcf89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-data-select2-unitSelect-result-a4a8-Pack</value>
      <webElementGuid>3e32f1ce-4b0a-4700-b8ca-5a5be809676d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a2646984-5ba0-498e-9aa3-e6429bf3453f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pack</value>
      <webElementGuid>d2801e33-847b-4b2e-a978-4d4372020e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-unitSelect-result-a4a8-Pack&quot;)</value>
      <webElementGuid>67eab76b-4e7b-471b-8aef-c630cea068c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-unitSelect-result-a4a8-Pack' and (text() = 'Pack' or . = 'Pack')]</value>
      <webElementGuid>96244cbc-b309-45b0-9bee-29e4af1cd835</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
