<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select Unit</name>
   <tag></tag>
   <elementGuidId>c19c244c-e469-49cb-8a91-866b67e61b5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='product-form']/div[5]/div[2]/div/div/div/div/span/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.select2.select2-container.select2-container--bootstrap5.select2-container--below.select2-container--open > span.selection > span.select2-selection.select2-selection--single.form-select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c86bce19-1c0f-45de-8635-e45f29d17c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection select2-selection--single form-select</value>
      <webElementGuid>1ea7a3ae-3bd9-4a12-a0d2-9f5d718507ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>ee7306bb-01ae-4c28-bdc6-228b3fc6f5a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2610e551-ca2b-4a74-aa5a-da6ca6e5b2a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0d157883-7202-4824-90cc-853ae86e0430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>10c733b9-4510-4ee6-9819-15cbdd6cae58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ab371654-2f8d-4e45-aeec-1a8b26666092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>select2-unitSelect-container</value>
      <webElementGuid>03a9f415-0500-49ae-a034-2b340a3e5ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>select2-unitSelect-container</value>
      <webElementGuid>44a7b48f-1969-452b-bbea-74b3e6c83578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>select2-unitSelect-results</value>
      <webElementGuid>60be61d2-8c75-43a2-8b64-d88c52443162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>select2-unitSelect-result-5xjt-Carton</value>
      <webElementGuid>9c6621a8-0b25-4818-84d3-908b58c38f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Unit</value>
      <webElementGuid>513c9f65-2abd-491a-b1a3-2cb6d4315681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-form&quot;)/div[@class=&quot;card card-flush mb-3&quot;]/div[@class=&quot;card-body py-4&quot;]/div[@class=&quot;align-items-center&quot;]/div[@class=&quot;row mb-2&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;form-group&quot;]/span[@class=&quot;select2 select2-container select2-container--bootstrap5 select2-container--below select2-container--open&quot;]/span[@class=&quot;selection&quot;]/span[@class=&quot;select2-selection select2-selection--single form-select&quot;]</value>
      <webElementGuid>aa3b5a82-2d8a-45e9-9bf6-878d075c79e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-form']/div[5]/div[2]/div/div/div/div/span/span/span</value>
      <webElementGuid>6e9cbef2-8357-4f4d-9681-900e80095496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::span[3]</value>
      <webElementGuid>191f5c9f-d42a-46c6-87a1-4d1fb5ea0d2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div/div/span/span/span</value>
      <webElementGuid>79b58bff-4136-4135-883e-2dd1cd9c539c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select Unit' or . = 'Select Unit')]</value>
      <webElementGuid>7be4e39c-0f33-4a49-9218-4600ac9380ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
