<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Upload Product_imageContainer1</name>
   <tag></tag>
   <elementGuidId>7160a5b1-16d8-4672-a3c6-f29b1fd22349</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#imageContainer1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='imageContainer1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>76f3e818-d8ab-40f0-8d80-0ddf60237851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imageContainer1</value>
      <webElementGuid>3f104ad5-3044-4ff5-a2dc-dbb4eeef6e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>triggerFileInput(1)</value>
      <webElementGuid>a54c942e-1f60-4117-b520-0166fa0b1e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imageContainer1&quot;)</value>
      <webElementGuid>a488fe40-8cb8-4670-891e-8a6d81effe9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='imageContainer1']</value>
      <webElementGuid>c7e72b60-1432-4973-b368-520e88a4831b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-form']/div/div[2]/div/div/div/div/div</value>
      <webElementGuid>fb9e3898-4478-4ab7-9a6e-4cf128a565df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Product'])[1]/following::div[6]</value>
      <webElementGuid>f894299b-ad95-487b-9874-840d7eea2045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setting'])[1]/following::div[19]</value>
      <webElementGuid>1cfad3a7-11a9-4dc4-8816-d5e4da66f49d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Information'])[1]/preceding::div[14]</value>
      <webElementGuid>a91c5078-eb8e-4f25-b42c-2a8e0f472c0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/div/div/div/div</value>
      <webElementGuid>ea853164-f0e9-4804-8a04-de8b6bd8bee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'imageContainer1']</value>
      <webElementGuid>f45bc453-6d43-43c6-8707-94e98bf98634</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
