<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__weight_is</name>
   <tag></tag>
   <elementGuidId>22b23837-9d2e-4d87-a1c9-a73961c30ee0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#weight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='weight']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ce31f4a-c52a-4fd8-856e-2a16f9247b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>2509fa8c-88a5-430f-bf3f-019d0ff8f2b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control w-50 mb-3</value>
      <webElementGuid>7ef6645d-8c69-4f1d-8793-613d8044d39a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>weight</value>
      <webElementGuid>770489eb-0756-4c87-bc72-f5b5b818ebad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>weight_is</value>
      <webElementGuid>257c632b-9be2-4791-8f45-0bb2a663cee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>emailHelp</value>
      <webElementGuid>84c45d4a-2bb4-4ae0-94aa-584c0d2f6b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Weight</value>
      <webElementGuid>d7afb1ef-ccf3-448f-8190-a8b7a53fa4fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;defaultDetail&quot;)/div[@class=&quot;align-items-center&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 my-1&quot;]/div[@class=&quot;input-group&quot;]/input[@id=&quot;weight&quot;]</value>
      <webElementGuid>cbf7d3b0-7469-4289-8f70-4474b99e7a4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='weight']</value>
      <webElementGuid>a9ab7d8a-7545-4089-9df7-b9f320858ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='defaultDetail']/div/div/div[2]/div/input</value>
      <webElementGuid>33b6fe3f-7d8b-40fd-a06d-60f4cb68c936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>839af932-9fe1-4d6d-8b7a-d0d8871b8411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'weight' and @name = 'weight_is' and @placeholder = 'Enter Weight']</value>
      <webElementGuid>b50536d2-d989-4d5b-9c4a-83b1dac7348d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
