<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__length</name>
   <tag></tag>
   <elementGuidId>4d1c7dba-6961-4b7e-951a-5936ea8aadee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#length</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='length']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1b7deee-1374-49e3-9e3e-729ceab60e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6b0202e9-545b-4bdb-b2f5-9aaebd94f8fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control w-50</value>
      <webElementGuid>9f6ce5d6-6332-4ac8-9fa9-88020569211b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>length</value>
      <webElementGuid>6ae58f80-58c3-463c-97b2-ef10e9bfeb49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>length</value>
      <webElementGuid>4f060249-bcd7-4254-a972-23da0efc346f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>emailHelp</value>
      <webElementGuid>351eb265-8467-4916-ae2c-7f0f63e47d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter length</value>
      <webElementGuid>7a65a808-77b3-421f-82db-18a149594507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;length&quot;)</value>
      <webElementGuid>8d32aabf-7f34-4744-9e40-b1ec1276a13d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='length']</value>
      <webElementGuid>6fca01a0-71dd-46f2-b62d-af09aece4fb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-form']/div[5]/div[2]/div/div[4]/div/div/input</value>
      <webElementGuid>895d78c8-cbbc-48cb-8673-7d7f41f9c0cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div/div/input</value>
      <webElementGuid>093feca1-b4ce-4e0d-8cfb-0f595ba67d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'length' and @name = 'length' and @placeholder = 'Enter length']</value>
      <webElementGuid>9502415e-228d-43f0-86e1-f0ae6f7724d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
