<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__barcode_is</name>
   <tag></tag>
   <elementGuidId>4c60c7c7-e90a-42a8-9bcb-85fa40a39d82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#barcode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='barcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6299d801-0b85-4f0b-9337-d3ea303cc439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d2ac9ef4-742a-4412-b56f-dda896dcc1d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1d11f620-cd07-4536-a065-62134cdb4a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>barcode</value>
      <webElementGuid>025d37ae-9690-4d3d-8f00-478536e7e01d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>barcode_is</value>
      <webElementGuid>3e9212e0-295d-41e7-8aed-d1c4890fc83a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>emailHelp</value>
      <webElementGuid>44579644-7ebb-45ab-94fe-c7361c34c88c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Product barcode</value>
      <webElementGuid>de7f019b-0beb-45c8-954f-99e2de9aa4c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;barcode&quot;)</value>
      <webElementGuid>43f659ca-1bfa-4031-a6cb-dfa01e781c55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='barcode']</value>
      <webElementGuid>1898eedd-cc46-48c8-878a-e5496c65d6b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='defaultDetail']/div/div[2]/div/input</value>
      <webElementGuid>b3f16d6a-6859-433e-95c1-5e5269ae61bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/input</value>
      <webElementGuid>95fb6dbb-23f1-4fa0-8b48-e04711bda76b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'barcode' and @name = 'barcode_is' and @placeholder = 'Enter Product barcode']</value>
      <webElementGuid>74ced29a-2614-4c6d-b2ec-95e101813367</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
