<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__weight</name>
   <tag></tag>
   <elementGuidId>f373de52-5865-495a-aa44-8dcbcf926aa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-md-4 > div.input-group > #weight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='weight'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>67e4b736-a794-4377-a1df-d6b1d4f2958d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cabbc187-102b-4bb1-b898-ab9150864614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control w-50</value>
      <webElementGuid>125d8641-f7a7-421c-93ba-f69ab3bbdaf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>weight</value>
      <webElementGuid>70f85d9f-eca8-4462-b7fd-cd3fa6a5e481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>weight</value>
      <webElementGuid>fa4830f6-bcf4-43e3-a72e-d21e3cb58e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>emailHelp</value>
      <webElementGuid>5c94230d-35af-4e5b-9286-7c25995884e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter weight</value>
      <webElementGuid>a3b7b3eb-485a-46a3-aaa8-4b814a257bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-form&quot;)/div[@class=&quot;card card-flush mb-3&quot;]/div[@class=&quot;card-body py-4&quot;]/div[@class=&quot;align-items-center&quot;]/div[@class=&quot;row mb-2&quot;]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;input-group&quot;]/input[@id=&quot;weight&quot;]</value>
      <webElementGuid>54207a6e-d09f-4c15-acb0-0765c6d678f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='weight'])[2]</value>
      <webElementGuid>9cdf559f-88b0-4001-b222-51db95bdbc9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-form']/div[5]/div[2]/div/div[3]/div/div/input</value>
      <webElementGuid>73e79473-b792-48e5-a085-43e4c5df4486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/div/input</value>
      <webElementGuid>d960f55a-fa23-4e0a-8047-80f101a17d7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'weight' and @name = 'weight' and @placeholder = 'Enter weight']</value>
      <webElementGuid>344efa76-3145-4008-b579-d8a716cd8bdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
