<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__hs_code_is</name>
   <tag></tag>
   <elementGuidId>c4c36045-2821-45b4-9aba-cef29dc21419</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hs_code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='hs_code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bbef8295-3eb6-4250-8f38-6c6d10921a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>85e93850-9c0c-4528-a254-69ebf71f079a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3a2d960f-7247-4b5d-b07b-87e1f35bccdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hs_code</value>
      <webElementGuid>1fd9bfa7-98b1-461e-961f-556955cc2b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hs_code_is</value>
      <webElementGuid>d1a97955-80f6-4d47-b92d-ec475a018955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>emailHelp</value>
      <webElementGuid>63f9632c-8926-4903-95e5-2ad3fa1c9170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter HS CODE</value>
      <webElementGuid>31bc4575-8702-4916-a0fe-9a6edfc5f499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hs_code&quot;)</value>
      <webElementGuid>401eb9ea-92a8-4a64-a395-080b0d4c1219</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='hs_code']</value>
      <webElementGuid>9191b18f-cedf-48ed-9a06-baa37022e18d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='defaultDetail']/div/div[2]/div[2]/input</value>
      <webElementGuid>b0d7c597-f055-4410-ab5a-aff022d9889b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>26bb7cc1-7f3b-46c8-96a0-cb1c28c724b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'hs_code' and @name = 'hs_code_is' and @placeholder = 'Enter HS CODE']</value>
      <webElementGuid>aadfff3e-ea48-404f-a9b6-f168124e8976</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
