<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IDR_price_is</name>
   <tag></tag>
   <elementGuidId>30dcca4a-be9c-4060-a55d-76794297afe6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-md-6.my-1 > div.input-group > #basic-url</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='basic-url'])[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a1d840a-90f9-4b32-89eb-47ecbe901390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>b9323cbb-8b6b-4c7f-a5c7-b8a8bbf829b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mb-3</value>
      <webElementGuid>ba29c3ec-ebc2-4b29-8371-6d2adc28233e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Price</value>
      <webElementGuid>f7a91495-37d9-470f-89b0-df87371f26f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>price_is</value>
      <webElementGuid>b38e7578-23d5-4cb6-8fe0-a53aa96799be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic-url</value>
      <webElementGuid>e8feaa3c-9e44-438f-aa13-68e997dc9073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>basic-addon3</value>
      <webElementGuid>e3b241ab-cf4c-4bed-868a-9c2145901ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;price-without-variant&quot;)/div[@class=&quot;col-md-6 my-1&quot;]/div[@class=&quot;input-group&quot;]/input[@id=&quot;basic-url&quot;]</value>
      <webElementGuid>a4677b2c-da18-419b-8a70-31da7325e2af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='basic-url'])[8]</value>
      <webElementGuid>d6af2b4b-8f9a-4717-a245-3c1140647e1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='price-without-variant']/div/div/input</value>
      <webElementGuid>ab43132d-a3ef-4c6c-a26e-c04fabd6c47e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>116e50fa-732f-41cd-b941-bbfa0fbd6736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = 'Enter Price' and @name = 'price_is' and @id = 'basic-url']</value>
      <webElementGuid>a5afb9ed-fb4e-4ad8-9b69-b417478c3409</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
