<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__stock_is</name>
   <tag></tag>
   <elementGuidId>2fe51261-f740-45b4-bed8-3f74ba8e5245</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#stock</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='stock']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>47838230-1b4d-472a-956c-dbd5c6cbc00d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>085cee64-ec74-425d-8e8f-c3ea18a322a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mb-3</value>
      <webElementGuid>f2bd5b16-337e-4c0e-98bc-072afb7d459e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>stock</value>
      <webElementGuid>b5852bf6-7bdb-40e5-a3e4-f3427306d51d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>stock_is</value>
      <webElementGuid>308264dd-4f66-4f2a-9940-5b90e87c42c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>emailHelp</value>
      <webElementGuid>3850ae29-a999-4685-ba0f-613fb393b992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Product Stock</value>
      <webElementGuid>d0cea9e0-2947-46ad-ac1a-220a911fdea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stock&quot;)</value>
      <webElementGuid>5956ecc8-51a6-4a4c-8277-9dcc201220c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='stock']</value>
      <webElementGuid>c5cbe9c7-f0c0-4dde-bd92-d2b50fae63bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='price-without-variant']/div[2]/input</value>
      <webElementGuid>668ef2d3-9f6b-4686-af59-3c7894b09546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div[2]/div[2]/input</value>
      <webElementGuid>f0968e66-a1bb-4f7a-9e52-8fb4331bb725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'stock' and @name = 'stock_is' and @placeholder = 'Enter Product Stock']</value>
      <webElementGuid>ca18731a-7785-41c4-8709-80fd53b4d98d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
