<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__sku_is</name>
   <tag></tag>
   <elementGuidId>eaf1bdda-b075-45e7-9763-3c1d2bb1fe71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sku</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sku']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b631bf4-d9d1-4875-98e8-be21b03d94b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3281ca03-6e8d-4977-a6dc-28722adb1602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mb-3</value>
      <webElementGuid>c8a5cdbf-a19b-47bc-bdc1-511cd5ecd338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sku</value>
      <webElementGuid>0b1c9838-7cd3-4a55-9fdb-7d029b939fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sku_is</value>
      <webElementGuid>42a27b6c-1597-40dc-ba00-bf2c970b72d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>emailHelp</value>
      <webElementGuid>71444cdf-8c8a-4bb6-b07c-03453d1f9486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Product SKU</value>
      <webElementGuid>77e0b40b-6872-4e62-9e18-7755fa53436f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sku&quot;)</value>
      <webElementGuid>49bbefde-c776-4e95-8831-b2f9c338231c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sku']</value>
      <webElementGuid>2f0237b2-02ad-4016-9995-3bcbc7d7c88f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='defaultDetail']/div/div/div/input</value>
      <webElementGuid>b9837b2b-ff3c-404b-a01d-5cdb95e58192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>f1e24fcd-6cf0-4912-b26a-5ae3b8775625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'sku' and @name = 'sku_is' and @placeholder = 'Enter Product SKU']</value>
      <webElementGuid>468964e6-4be7-4627-95b7-ba53a0b3b909</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
