<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Meat</name>
   <tag></tag>
   <elementGuidId>60901a20-7604-4269-b543-d28f9da4738a</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-category-result-y9nd-1148ecea-0017-454b-a0e9-31d62af5417c']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-category-result-y9nd-1148ecea-0017-454b-a0e9-31d62af5417c</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//li[(text() = ' Meat ' or . = ' Meat ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>969d4375-a265-46a4-ae95-c7fea985e949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--selectable select2-results__option--selected select2-results__option--highlighted</value>
      <webElementGuid>1d3c9f1b-f3c6-451f-ac8e-352c4f2dbb1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-category-result-y9nd-1148ecea-0017-454b-a0e9-31d62af5417c</value>
      <webElementGuid>ce881e0f-d1db-41ad-aaf4-d113deba112d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>4e01c2a7-582e-4c42-864a-888531e26f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-data-select2-category-result-y9nd-1148ecea-0017-454b-a0e9-31d62af5417c</value>
      <webElementGuid>bdbff0b1-e18e-4632-b049-2451b2c05a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c2dcd0f1-8568-4b13-9257-3ecd19c991e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Meat </value>
      <webElementGuid>c4ca04a1-b0d4-43d3-8c0b-5e87e3664b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-category-result-y9nd-1148ecea-0017-454b-a0e9-31d62af5417c&quot;)</value>
      <webElementGuid>62decbce-b6d0-4f27-9504-6bed000c5b6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-category-result-y9nd-1148ecea-0017-454b-a0e9-31d62af5417c']</value>
      <webElementGuid>6036984b-fe37-4f44-ac51-b635643a7552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-category-results']/li[2]</value>
      <webElementGuid>ed606624-0444-4228-9956-17cabfc4837b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Category'])[2]/following::li[1]</value>
      <webElementGuid>ee45f892-c54c-4aaf-a5cf-1c540e0962eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'select2-category-result-y9nd-1148ecea-0017-454b-a0e9-31d62af5417c', '&quot;', ')')])[1]/following::li[2]</value>
      <webElementGuid>0f413cdb-43d2-4481-ac63-8184c9f50bfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul/li[2]</value>
      <webElementGuid>98d3d63a-7d71-47db-8755-2c6d3cb242d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-category-result-y9nd-1148ecea-0017-454b-a0e9-31d62af5417c' and (text() = ' Meat ' or . = ' Meat ')]</value>
      <webElementGuid>b2146b4f-6295-40d1-b84c-e12f660b93fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
