<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_GramsK.GLML</name>
   <tag></tag>
   <elementGuidId>2ba83fb4-e668-4da4-aceb-161a4a4dcae8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;sub_weight_is&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='sub_weight_is']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c029f791-db98-45fa-8cf3-cee40d99cb70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-group-text form-select mb-3</value>
      <webElementGuid>4aa3637f-1c08-443a-9ce9-6476b355d088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sub_weight_is</value>
      <webElementGuid>c1584c84-0189-4d68-899b-de985e2673b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GramsK.GLML</value>
      <webElementGuid>4556da69-aca4-406f-9ccc-bd3870a4afc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;defaultDetail&quot;)/div[@class=&quot;align-items-center&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 my-1&quot;]/div[@class=&quot;input-group&quot;]/select[@class=&quot;input-group-text form-select mb-3&quot;]</value>
      <webElementGuid>a18665b8-2bf2-4de0-b37b-0bce76249928</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='sub_weight_is']</value>
      <webElementGuid>40e8b937-0b59-47cf-8280-d8a5dcd6f76a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='defaultDetail']/div/div/div[2]/div/select</value>
      <webElementGuid>b3993f00-0ef2-4886-8712-27a6e3915a6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::select[1]</value>
      <webElementGuid>b6431a51-e01a-4528-8182-8630dafaf909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/preceding::select[1]</value>
      <webElementGuid>1a8ba840-b0d2-4bfe-b4af-037e56781a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div/div[2]/div/select</value>
      <webElementGuid>baa40434-7011-4294-957b-ec0e5aa3a788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'sub_weight_is' and (text() = 'GramsK.GLML' or . = 'GramsK.GLML')]</value>
      <webElementGuid>357ad9df-0642-451c-bf8a-c07ff00e78fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
